name: sakha_radio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.36
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  html: ^0.15.4
  provider: ^6.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bg_dark.png
    - assets/bg_light.png
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256
